contact_links:
  - name:  Script Hook V Issue for New Game Version
    url: http://www.dev-c.com/gtav/scripthookv/
    about: |
      This issue tracker is not for the Script Hook V issue where "FATAL: Unknown game version" appears. Please be patient until a new ScriptHookV update is released.
  - name: 🤔 Questions and Help
    url: https://github.com/scripthookvdotnet/scripthookvdotnet/discussions
    about: This issue tracker is not for support questions. Please seek your support help in Discussions page on this repository or other communities, such as 5Mods Discord server or its forum.